---
- name: usuarios padroes
  user: 
    name: "{{item.nome}}"
    shell: "{{item.bash}}"
    password: "{{item.senha}}"
    home: "{{item.home}}"
  with_items:
    - {nome: samuel, bash: /bin/bash, senha: '$1$c3AQmyxr$bcJIGHv9S6jCTPtbTwbAL1', home: /home/samuel }
    - {nome: developer, bash: /bin/bash, senha: '$1$c3AQmyxr$bcJIGHv9S6jCTPtbTwbAL1', home: /home/developer }
    - {nome: devops, bash: /bin/bash, senha: '$1$c3AQmyxr$bcJIGHv9S6jCTPtbTwbAL1', home: /home/devops }
