---
 - name: cp aquivos default maquinas
   copy:
   src: "{{item.origem}}"
   dest: "{{item.desitno}}"
  with_items:
    - { origem: files/host, destino: /etc/hosts }
    - { origem: files/resolv, destino: /etc/resolv.conf }
  
