---
- name: add pack
  hosts: all
  tasks:
   - name: install
     package:
       name: 
        - httpd2
       state: present
   - name: envia arq
     copy:
       src: /etc/hosts
       dest: /etc/hosts
   - name: nova linha
     lineinfile:
       path: /etc/hosts
       line: '192.168.200.1 desktop'
   - name: bloco de config
     blockinfile:
       path: /etc/hosts
       block: |
         192.168.0.10 desktop1
         111.112.3.12 desktop2 
